## U need to install REST extension from VS marketplace to make it work

###
## Lists all items in data store
GET http://localhost:8080/api/v1/items

###
## Get item by unique id
GET http://localhost:8080/api/v1/items/db0fd8ee-6a89-4684-8379-f19d73c12afc

###
POST http://localhost:8080/api/v1/items
content-type: application/json

{
    "name": "Krzysztof",
    "price": 123,
    "description": "TBD",
    "sku": "TBD"
}

###
PUT http://localhost:8080/api/v1/items
content-type: application/json

{
    "id" : "db0fd8ee-6a89-4684-8379-f19d73c12afc",
    "price": 123,
    "name": "chris",
    "description": "TBD",
    "sku": "TBD"
}

###
## Delete item by unique id
DELETE  http://localhost:8080/api/v1/items/00000000-0000-0000-0000-000000000000
