basePath: /api/v1
definitions:
  data.Item:
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: number
      sku:
        type: string
    required:
    - id
    - name
    - price
    type: object
host: localhost:8080
info:
  contact:
    email: krzysztof.lach@icloud.com
    name: API Support
    url: TBD
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: TBD
  title: Items Store Go Example API
  version: "1.0"
paths:
  /items:
    get:
      consumes:
      - application/json
      description: List items
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/data.Item'
            type: array
      summary: Gets all items from database
      tags:
      - listAll
  /items/{id}:
    get:
      consumes:
      - application/json
      description: Get item by id
      parameters:
      - description: Item guid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.Item'
      summary: Get item by unique id
      tags:
      - byId
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
