trigger:
- main

parameters:
- name: deployInfrastructure
  displayName: Deploy Infrastructure
  type: boolean
  default: 'false'

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureResourceManagerConnection: 'VSE(8b85a152-5ad9-43dd-838e-a26bc50d0d8d)'
  subscriptionId: '8b85a152-5ad9-43dd-838e-a26bc50d0d8d'
  azureSubscriptionName: 'Subskrypcja programu Visual Studio Enterprise (8b85a152-5ad9-43dd-838e-a26bc50d0d8d)'

  rgName: 'akstestrg'

  # Agent VM image name
  vmImageName: 'ubuntu-20.04'

  # Working Directory
  workingDirectory: '$(Pipeline.Workspace)/Items.Store.Api'

stages:
- stage: 'Infrastructure'
  displayName: 'Deploy AKS Infrastructure'
  
  jobs: 
  - job: 'Deploy'
    displayName: 'Deploy AKS'
    pool:
      vmImage: $(vmImageName)

    steps:
    # ################################################# ARM DEPLOYMENT #############################################################
    # - task: CopyFiles@2
    #   name: PrepareInfrastructureTemplates  
    #   condition: and(succeeded(), eq(${{ parameters.deployInfrastructure }}, 'true'))
    #   inputs:
    #     SourceFolder: 'deployment/infrastructure'
    #     Contents: '**'
    #     TargetFolder: '$(build.artifactstagingdirectory)/deployment/infrastructure'

    # - task: AzureResourceManagerTemplateDeployment@3
    #   name: DeployKubernetesInfrastructure
    #   condition: and(succeeded(), eq(${{ parameters.deployInfrastructure }}, 'true'))
    #   inputs:
    #       deploymentScope: 'Subscription'
    #       azureResourceManagerConnection: 'VSE(8b85a152-5ad9-43dd-838e-a26bc50d0d8d)'
    #       subscriptionId: '8b85a152-5ad9-43dd-838e-a26bc50d0d8d'
    #       action: 'Create Or Update Resource Group'
    #       resourceGroupName: 'akstestrg'
    #       location: 'West Europe'
    #       templateLocation: 'Linked artifact'
    #       csmFile: '$(build.artifactstagingdirectory)/deployment/infrastructure/template.json'
    #       csmParametersFile: '$(build.artifactstagingdirectory)/deployment/infrastructure/parameters.json'
    #       deploymentMode: 'Incremental'
    #       deploymentName: 'DeployAKSInfrastructure'
    # ##############################################################################################################

    # https://azuredevopslabs.com/labs/vstsextend/ansible/