trigger:
- none

parameters:
- name: deployAKSInfrastructure
  displayName: Deploy Infrastructure
  type: boolean
  default: 'false'
- name: deployDockerInfrastructure
  displayName: Deploy Infrastructure
  type: boolean
  default: 'false'

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureResourceManagerConnection: 'VSE(8b85a152-5ad9-43dd-838e-a26bc50d0d8d)'
  subscriptionId: '8b85a152-5ad9-43dd-838e-a26bc50d0d8d'
  azureSubscriptionName: 'Subskrypcja programu Visual Studio Enterprise (8b85a152-5ad9-43dd-838e-a26bc50d0d8d)'
  RESOURCE_GROUP: akstestrg 
  CLUSTER_NAME: aks-testing-ziqq 
  LOCATION: westeurope 
  rgName: 'akstestrg'

  # Agent VM image name
  vmImageName: 'ubuntu-20.04'

  # Working Directory
  workingDirectory: '$(Pipeline.Workspace)/Items.Store.Api'

stages:
- stage: 'Infrastructure'
  displayName: 'Deploy AKS Infrastructure'
  
  jobs: 
  - job: 'Deploy'
    displayName: 'Deploy AKS'
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: AzureCLI@2
      name: DeployAksInfrastructure
      condition: and(succeeded(), eq(${{ parameters.deployAKSInfrastructure }}, 'true'))
      inputs:
        azureSubscription: 'VSE(8b85a152-5ad9-43dd-838e-a26bc50d0d8d)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks create \
              --resource-group $RESOURCE_GROUP\
              --name $CLUSTER_NAME \
              --node-count 1 \
              --enable-addons http_application_routing \
              --generate-ssh-keys \
              --node-vm-size Standard_B2ms \
              --network-plugin azure
        arguments: '$(RESOURCE_GROUP) $(CLUSTER_NAME) $(LOCATION)'

    # ####################### For some reason ARM templates are not working as they suppose to... 
    # ##[error]ResourceNotFound: The Resource 'Microsoft.ContainerRegistry/registries/ziqqdcr' under resource group '<null>' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
    #
    #
    #
    # - task: CopyFiles@2
    #   name: PrepareInfrastructureTemplates  
    #   condition: and(succeeded(), eq(${{ parameters.deployDockerInfrastructure }}, 'true'))
    #   inputs:
    #     SourceFolder: 'deployment/infrastructure'
    #     Contents: '**'
    #     TargetFolder: '$(build.artifactstagingdirectory)/deployment/infrastructure'

    # - task: AzureResourceManagerTemplateDeployment@3
    #   name: DeployKubernetesInfrastructure
    #   condition: and(succeeded(), eq(${{ parameters.deployDockerInfrastructure }}, 'true'))
    #   inputs:
    #       deploymentScope: 'Subscription'
    #       azureResourceManagerConnection: 'VSE(8b85a152-5ad9-43dd-838e-a26bc50d0d8d)'
    #       subscriptionId: '8b85a152-5ad9-43dd-838e-a26bc50d0d8d'
    #       action: 'Create Or Update Resource Group'
    #       resourceGroupName: 'akstestrg'
    #       location: 'West Europe'
    #       templateLocation: 'Linked artifact'
    #       csmFile: '$(build.artifactstagingdirectory)/deployment/infrastructure/template.json'
    #       csmParametersFile: '$(build.artifactstagingdirectory)/deployment/infrastructure/parameters.json'
    #       deploymentMode: 'Incremental'
    #       deploymentName: 'DeployDockerContainerRegistry'